#!/usr/bin/env bash
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_CURRENT_DESKTOP=Hyprland
export GDK_BACKEND="wayland"
export ELECTRON_OZONE_PLATFORM_HINT=wayland
export WAYLAND_DISPLAY="wayland-0"
export DISPLAY="wayland-0"
export QT_QPA_PLATFORM="wayland;xcb"
export SDL_VIDEODRIVER="wayland"
export CLUTTER_BACKEND="wayland"
export STEAM_FORCE_DESKTOPUI_SCALING=1
export XCURSOR_SIZE=20
export XCURSOR_THEME=Bibata-Modern-Ice
export HYPRCURSOR_SIZE=20
export HYPRCURSOR_THEME=Bibata-Modern-Ice
export GTK_THEME=pop:dark
export QT_QPA_PLATFORMTHEME=qt6ct
exec Hyprland